scrape_configs:
  ## Redis Exporter가 여러 Redis 대상을 scrape하는 설정
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
          - redis://redis-1:7001
          - redis://redis-2:7002
          - redis://redis-3:7003
          - redis://redis-4:7004
          - redis://redis-5:7005
          - redis://redis-6:7006
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9121

  ## exporter 자체의 메트릭 scrape 설정
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
          - redis_exporter:9121
